import { useMemo } from 'react'
import katex from 'katex'

/** Render a KaTeX formula. Content is generated by the app itself (numbers
 * from the real model), never raw user input — safe to set as HTML. */
export function MathBlock({ tex, block = true, className = '' }: { tex: string; block?: boolean; className?: string }) {
  const html = useMemo(() => {
    try {
      return katex.renderToString(tex, { displayMode: block, throwOnError: false })
    } catch {
      return `<span class="text-rose-400">invalid formula</span>`
    }
  }, [tex, block])
  return <span className={`overflow-x-auto ${block ? 'block' : 'inline-block'} ${className}`}
    dangerouslySetInnerHTML={{ __html: html }} />
}
